
# This workflow is for the website page
# The workflow also is a starting file that is used for learning.

name: Family Recipe Workflow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    - uses: actions/checkout@v1
      - name: Install Node
        uses: actions/setup-node@v1
          with:
              node-version: 12.8
      - name: npm dependencies
        run: npm install     
      - name: Build
        run: npm run build -- --prod

      - run: npm run lint
      - run: npm run build --if-present

